apiVersion: v1
kind: ConfigMap
metadata:
  name: ms-config
  namespace: ecommerce
data:
  PRODUCT_SERVICE_URL: "http://product-service:8002"
  NOTIFICATION_SERVICE_URL: "http://notification-service:8004"

---
apiVersion: v1
kind: Secret
metadata:
  name: ms-secret
  namespace: ecommerce
type: Opaque
stringData:
  MONGO_URI_USER: "mongodb://user-mongo:27017"
  MONGO_URI_PRODUCT: "mongodb://product-mongo:27017"
  MONGO_URI_ORDER: "mongodb://order-mongo:27017"
  MONGO_URI_NOTIF: "mongodb://notification-mongo:27017"
  JWT_SECRET: "supersecretjwtkey_123"
